### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by NewDay1313** [piccolo-orm/piccolo#111] opened 2021-06-14 19:05 UTC
Running Postgres version 13.3
Running migrations ...
All migration ids = ['2021-06-14T23:35:51', '2021-06-14T23:45:55', '2021-06-14T23:53:23', '2021-06-14T23:57:34']
Haven't run = ['2021-06-14T23:35:51', '2021-06-14T23:45:55', '2021-06-14T23:53:23', '2021-06-14T23:57:34']
Running MigrationManager ...
**The command failed.
user is a protected name, please give your table a different name.** 

I don't have any table with this name. 

Before that there was table naming error! 
```
manager.add_table("Sessions", tablename="sessions")
manager.add_table("SessionsBase", tablename="sessions")  
```

**Comment by dantownsend** [comment] 2021-06-14 19:20
@NewDay1313 Piccolo checks in case a `Table` has a tablename of `'user'`.  For example, either of these:

```python
class User(Table):
    ...

class MyTable(Table, tablename='user'):
    ...
```

It's because `user` is a reserved word in Postgres, and having a table with the same name would cause issues.

Do you think that's the case here?

**Comment by NewDay1313** [comment] 2021-06-14 19:32
> It's because `user` is a reserved word in Postgres, and having a table with the same name would cause issues

Got it! It explains everything!

> Do you think that's the case here?

Definetly It takes place here!

**Comment by Anonymous1313-tech** [comment] 2021-06-15 15:29
So will you change that table name in piccolo?

**Comment by dantownsend** [comment] 2021-06-15 16:47
I don't think any of the builtin migrations for Piccolo use a tablename of `user`.

Check any migration files which Piccolo has created for you, in case any of the reference a table called `user`.

If you want you can paste the code here and I'll take a look.

**Comment by heliumbrain** [comment] 2021-06-28 08:55
@dantownsend playing around with this last night I noticed that there might be some inconsistency in how the PROTECTED_NAME check is applied.

in piccolo/table.py:148
```python
        tablename = tablename if tablename else _camel_to_snake(cls.__name__)

        if tablename in PROTECTED_TABLENAMES:
            raise ValueError(
                f"{tablename} is a protected name, please give your table a "
                "different name."
            )
```

Can't figure out why, but it seems that tablename will always resolve to `cls.__name__`

For example, when inheriting from BaseUser:

```python
class User(BaseUser, tablename="my_users"):
    pass
```

The migrations are succesfully generated (using `piccolo migrations new my_app --auto`)  with `manager.add_table("User", tablename="my_users")`

How ever, trying to push the migrations with `piccolo migrations forwards my_app` gives the same error as mentioned in this thread:

`user is a protected name, please give your table a different name.`

**Comment by dantownsend** [comment] 2021-06-28 20:05
@heliumbrain You're right, there is an issue. Good catch.

The problem is here:

https://github.com/piccolo-orm/piccolo/blob/49562c2c94540c219f7b67ccaf180a3bbf48787d/piccolo/apps/migrations/auto/migration_manager.py#L562-L570

Piccolo creates a `Table` class, but only sets the tablename afterwards, so it's triggering this warning when the table is called 'user'. I'll have a read of the docs for `type` to see if parameters can be passed to it.

**Comment by dantownsend** [comment] 2021-06-28 20:38
Looks like `types.new_class` will do the trick:

https://docs.python.org/3/library/types.html#types.new_class

**Comment by heliumbrain** [comment] 2021-06-28 21:14
Yeah, looks good! I can have a shot at fixing it tomorrow, if you're not on it already @dantownsend :)

**Comment by dantownsend** [comment] 2021-06-29 06:18
Should be fixed now - I've push a new build to PyPI.

**Comment by dantownsend** [comment] 2021-06-30 12:38
Closing for now - let me know if the problem still persists. Thanks

**Closed by dantownsend** 2021-06-30 12:38 UTC
